import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../component/navbar'
import Header from '../component/index/header'
import TestimonialsMain from '../component/index/testimonials'
import WhyBlock from '../component/index/whyBlock'
import MoreTools from '../component/index/moreTools'
import FooterMenu from '../component/index/footerMenu'
import Footer from '../component/footer';
import cookies from 'js-cookie';
import 'cors';
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

  const [index, setIndex] = useState(true);

  const token = cookies.get('jwt');
  //  console.log(token);
  const tokenData = {
    token: token
  }
  // console.log(JSON.stringify(tokenData));

  const check = async () => {
    try {
      const res = await fetch("https://fliacrtserver.onrender.com/login", {
        method: 'post',
        headers: {
          'content-type': "application/json"
        },
        mode: 'cors',
        body: JSON.stringify(tokenData)
      })
      // console.log(token);
      const result = await res.json();
      console.log(`Login Check: ${res.status}`);
      if (res.status == 200) {
        setIndex(false);
        router.push('/onboarding');
      } else {
        router.push('/');
      }

    } catch (error) {
      console.log(`error: ${error}`);
      router.push('/');
    }

  }

  let init = false;
  useEffect(() => {
    if(!init){
      init = true;
      check();
    }
    
  }, []);
  

  return (
    <>
      <Head>
        <title>Sell online- become a online seller in india | Flicart Seller Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav.ico" />
      </Head>
      <div style={{ "display": index ? "block" : "none" }}>
        <Navbar />
        <br />
        <Header />
        <br />
        <TestimonialsMain />
        <br />
        <hr />
        <br /><br />
        <WhyBlock />
        <br />
        <MoreTools />
        <br />
        <FooterMenu />
        <br /><br />
        <Footer />
      </div>
    </>
  )
}
