import { useEffect, useState } from 'react';
import Head from 'next/head'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import styles from '../styles/signUp.module.css'
import { useRouter } from 'next/router';
import cookie from 'react-cookies';
import cookies from 'js-cookie';
import 'cors';

export default function SignUp() {
    const router = useRouter();

    const [signUp, setSignUp] = useState(true);
    const token = cookies.get('jwt');
    //  console.log(token);
    const tokenData = {
        token: token
    }
    // console.log(JSON.stringify(tokenData));

    const check = async () => {
        try {
            const res = await fetch("https://fliacrtserver.onrender.com/login", {
                method: 'post',
                headers: {
                    'content-type': "application/json"
                },
                mode: 'cors',
                body: JSON.stringify(tokenData)
            })
            // console.log(token);
            const result = await res.json();
            console.log(`Login: ${res.status}`);
            if (res.status == 200) {
                setSignUp(false);
                router.push('/onboarding');
            } else {
                router.push('/signUp');
            }

        } catch (error) {
            console.log(`error: ${error}`);
            router.push('/signUp');
        }

    }

    let init = false;
    useEffect(() => {
        if (!init) {
            init = true;
            check();
        }

    }, []);



    const {
        query: { mobile }
    } = router;

    const props = {
        mobile
    }

    const [seller, setSeller] = useState({
        mobileSet: mobile,
        email: "",
        gst: "",
        pan: "",
        password: "",
        cpassword: ""
    })

    const inputHandle = (e) => {
        const name = e.target.name;
        const value = e.target.value;
        setSeller({ ...seller, [name]: value })
    }


    const notify = () => toast("Wow Next you Create Password!");
    const allCategory = () => toast("You select All Categories!");
    const bookCategory = () => toast("You select Book Categories!");
    const [firstH2, setfirstH2] = useState(true);
    const [secondH2, setsecondH2] = useState(false);
    const [gstDiv, setgstDiv] = useState(true);
    const [panDiv, setpanDiv] = useState(false);
    const [green, setGreen] = useState({
        green1: true,
        green2: true,
        green3: true
    })

    const [passwordSection, setPasswordSection] = useState(false);
    const [mobileEmailSection, setMobileEmailSection] = useState(true);

    function hideShow1() {
        setfirstH2(true);
        setsecondH2(false);
        setgstDiv(true);
        setpanDiv(false);
        allCategory();
    }
    function hideShow2() {
        setfirstH2(false);
        setsecondH2(true);
        setgstDiv(false);
        setpanDiv(true);
        bookCategory();
    }


    function gstMobileEmail() {
        if (!seller.email || !seller.mobileSet) {
            // alert(seller.email + " "+ seller.mobileSet);
            toast("Please Fill All the Details!");
        } else {
            // alert(seller.email);
            notify();
            const name = "green1";
            setGreen({ ...green, [name]: false })
            setPasswordSection(true);
            setMobileEmailSection(false);

        }

    }
    const infoSend = async () => {
        try {

            const res = await fetch("https://fliacrtserver.onrender.com/sellerRegistration", {
                method: 'post',
                headers: {
                    'Content-Type': "application/json"
                },
                mode: 'cors',
                body: JSON.stringify(seller)
            })
            const result = await res;
            const message = await res.json();
            if (result.status == 400) {toast("You Not Register!"); setPasswordSection(false); setMobileEmailSection(true); return console.log(`Data Not Insert.`) }
            console.log(message.token)
          
            if (result.status == 200) {  cookie.save('jwt', message.token, { path: '/' }); router.push("/onboarding"); return console.log(`Data Insert.`) }

            if(result.status ==300){  const name = "green1"; setGreen({ ...green, [name]: true }); toast("You Alredy Register this Number!"); setPasswordSection(false); setMobileEmailSection(true)}

        } catch (error) {
            console.log(`error: ${error}`)
        }

    }

    return (
        <>
            <ToastContainer />
            <Head>
                <title>Seller Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/fav.ico" />
            </Head>

            <div style={{ "display": signUp ? "block" : "none" }}>
                {/* Nav Sectioon Strat */}
                <div className={styles.navBar}>
                    <div className={styles.logos}>
                        <img width='30px' src="/logoPic.png" alt="logo" />
                        <img width='30px' src="/logoPic.png" alt="logo" />
                    </div>

                    <div className={styles.menuBar}>
                        <div className={styles.flex}>
                            <img width='15px' src="/checked.png" alt="" style={{ "display": green.green1 ? "block" : "none" }} />
                            <img width='15px' src="/correct.png" alt="" style={{ "display": green.green1 ? "none" : "block" }} />
                            <h3>EMAIL ID & GST</h3>
                        </div>

                        <div className={styles.line}>
                            <h2>__</h2>
                        </div>

                        <div className={styles.flex}>
                            <img width='15px' src="/checked.png" alt="" style={{ "display": green.green2 ? "block" : "none" }} />
                            <img width='15px' src="/correct.png" alt="" style={{ "display": !(green.green2) ? "block" : "none" }} />
                            <h3>PASSWORD CREATION</h3>
                        </div>

                        <div className={styles.line}>
                            <h2>__</h2>
                        </div>

                        <div className={styles.flex}>
                            <img width='15px' src="/checked.png" alt="" style={{ "display": green.green3 ? "block" : "none" }} />
                            <img width='15px' src="/correct.png" alt="" style={{ "display": !(green.green3) ? "block" : "none" }} />
                            <h3>ONBOARDING DASHBOARD</h3>
                        </div>

                    </div>
                </div>
                {/* Nav section end */}

                {/* Form Section start */}

                <div className={styles.formsection}>
                    <div className={styles.main}>


                        <div className={styles.formMain} style={{ "display": mobileEmailSection ? "block" : "none" }} >

                            <div className={styles.enterMobile}>
                                <input onChange={inputHandle} type="text" placeholder='Enter Mobile Number' name='mobileSet' value={seller.mobileSet} />
                            </div>

                            <div className={styles.enterMobile}>
                                <input onChange={inputHandle} type="email" name='email' value={seller.email} placeholder='Enter Email ID' />
                            </div>

                            <h2>What are you looking to sell on Flipkart?</h2>
                            <br />
                            <div className={styles.categories}>

                                <div onClick={hideShow1} className={styles.btn1} style={{ "backgroundColor": firstH2 ? "#ebf3fb" : "#fff", "border": firstH2 ? "1px solid #0066cc" : "1px solid #000" }}>
                                    <img width="25px" height="25px" src="/box.png" alt="box" />
                                    <h2 style={{ "color": firstH2 ? "#0066cc" : "#000" }}>All Categories</h2>
                                </div>

                                <div onClick={hideShow2} className={styles.btn2} style={{ "backgroundColor": secondH2 ? "#ebf3fb" : "#fff", "border": secondH2 ? "1px solid #0066cc" : "1px solid #000" }}>
                                    <img width="25px" height="25px" src="/box.png" alt="box" />
                                    <div>
                                        <h2 style={{ "color": secondH2 ? "#0066cc" : "#000" }}>Only Books</h2>
                                        <h5 style={{ "color": secondH2 ? "#0066cc" : "#000" }}>(PAN is mandatory)</h5>
                                    </div>
                                </div>

                            </div>

                            <div style={{ "display": gstDiv ? "block" : "none" }}>
                                <div className={styles.gst}>

                                    <div className={styles.enterGst}>
                                        <input onChange={inputHandle} type="text" name='gst' value={seller.gst} placeholder='Enter GSTIN' />
                                    </div>

                                </div>
                            </div>


                            <h2 style={{ "display": firstH2 ? "block" : "none" }}>GSTIN is required to sell products on Flipkart. You can also share it in the final step.</h2>

                            <div style={{ "display": panDiv ? "block" : "none" }}>
                                <div className={styles.gst}>

                                    <div className={styles.enterGst}>
                                        <input onChange={inputHandle} type="text" name='pan' value={seller.pan} placeholder='Enter PAN Number' />
                                    </div>

                                </div>

                            </div>

                            <h2 style={{ "display": secondH2 ? "block" : "none" }}>PAN is required to sell books on Flipkart. You can also share it in the final step.</h2>

                            <br />
                            <div className={styles.registrationDiv}>
                                <h5>By continuing, I agree to Flipkart’s <a href="#">Terms of Use</a>  & <a href="#">Privacy Policy</a> </h5>
                                <br />
                                <button onClick={gstMobileEmail}> Countinue  <img width="40px" src="/right-arrow.png" alt="arrow" /></button>
                            </div>
                        </div>

                        {/* Password Creation Part Start */}
                        <div className={styles.passwordCreationSection} style={{ "display": passwordSection ? "block" : "none" }}>
                            <div className={styles.formMain}>

                                <div className={styles.enterMobile}>
                                    <input name='password' value={seller.password} onChange={inputHandle} type="password" placeholder='Enter Password' />
                                </div>

                                <div className={styles.enterMobile}>
                                    <input name='cpassword' value={seller.cpasswortd} onChange={inputHandle} type="text" placeholder='Repeat Password' />
                                </div>

                                <br />
                            </div>
                            <br />
                            <div className={styles.registrationDiv}>
                                <h5>By continuing, I agree to Flipkart’s <a href="#">Terms of Use</a>  & <a href="#">Privacy Policy</a> </h5>
                                <br />
                                <button onClick={infoSend}>Register <img width="40px" src="/right-arrow.png" alt="arrow" /></button>
                            </div>
                        </div>


                        <div className={styles.detailShowCase}>

                            <div className={styles.testy}>
                                <div className={styles.imagetesty}>
                                    <img width="50px" height="50px" src="/box.png" alt="logo" />
                                </div>

                                <div className={styles.comment}>
                                    <h5>
                                        Starting with 1, Flipkart helped me expand to 6 categories with 5x growth year on year!
                                    </h5>
                                    <h6>
                                        Raju Lunawath, Amazestore
                                    </h6>
                                </div>

                            </div>

                        </div>

                    </div>

                </div>

                {/* Footer Desgne */}
                <br /><br />
                <div className={styles.footersection}>

                    <h1>Why sell on Flicart?</h1>

                    <div className={styles.flexWrap}>

                        <div className={styles.flexSize}>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/truck2.png" alt="truck" />
                                </div>
                                <h3>Sell Across India</h3>
                                <p>Reach over 50 crore+ customers across 27000+ pincodes</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/zero2.png" alt="zero" />
                                </div>
                                <h3>Higher Profits</h3>
                                <p>With 0% commission* , you take 100% profits with you</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/user.png" alt="truck" />
                                </div>
                                <h3>Account Management</h3>
                                <p>Our Dedicated managers will help your business on Flipkart</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/low-price.png" alt="low price" />
                                </div>
                                <h3>Lower Return Charges</h3>
                                <p>With our flat and low return charges, ship your products stress-free</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/calculator.png" alt="calculator" />
                                </div>
                                <h3>Simple Pricing Calculator</h3>
                                <p>Use our simple pricing calculator to decide the best and competitive selling price for your product</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/headphones.png" alt="head phone" />
                                </div>
                                <h3>24x7 Seller Support</h3>
                                <p>All your queries and issues are answered by our dedicated Seller Support Team</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/rupee.png" alt="rupee" />
                                </div>
                                <h3>Fast & Regular Payments</h3>
                                <p>Get payments as fast as 7-10 days from the date of dispatch</p>
                            </div>

                            <div className={styles.infoSection}>
                                <div className={styles.imagestyle}>
                                    <img height="50px" width="50px" src="/phonefram.png" alt="phone" />
                                </div>
                                <h3>Business on the go</h3>
                                <p>Download our Flipkart Seller App to manage your business anywhere, anytime</p>
                            </div>

                        </div>

                    </div>

                </div>
            </div>

        </>
    )
}
